// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(flowsdk_ffi)
import flowsdk_ffi
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_flowsdk_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_flowsdk_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol MqttEngineFfiProtocol : AnyObject {
    
    func auth(reasonCode: UInt8) 
    
    func connect() 
    
    func disconnect() 
    
    func getVersion()  -> UInt8
    
    func handleConnectionLost() 
    
    func handleIncoming(data: Data)  -> [MqttEventFfi]
    
    func handleTick(nowMs: UInt64)  -> [MqttEventFfi]
    
    func isConnected()  -> Bool
    
    func nextTickMs()  -> Int64
    
    func publish(topic: String, payload: Data, qos: UInt8, priority: UInt8?)  -> Int32
    
    func pushEventFfi(event: MqttEventFfi) 
    
    func subscribe(topicFilter: String, qos: UInt8)  -> Int32
    
    func takeEvents()  -> [MqttEventFfi]
    
    func takeOutgoing()  -> Data
    
    func unsubscribe(topicFilter: String)  -> Int32
    
}

open class MqttEngineFfi:
    MqttEngineFfiProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_flowsdk_ffi_fn_clone_mqttengineffi(self.pointer, $0) }
    }
public convenience init(clientId: String?, mqttVersion: UInt8) {
    let pointer =
        try! rustCall() {
    uniffi_flowsdk_ffi_fn_constructor_mqttengineffi_new(
        FfiConverterOptionString.lower(clientId),
        FfiConverterUInt8.lower(mqttVersion),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_flowsdk_ffi_fn_free_mqttengineffi(pointer, $0) }
    }

    
public static func newWithOpts(opts: MqttOptionsFfi) -> MqttEngineFfi {
    return try!  FfiConverterTypeMqttEngineFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_constructor_mqttengineffi_new_with_opts(
        FfiConverterTypeMqttOptionsFFI.lower(opts),$0
    )
})
}
    

    
open func auth(reasonCode: UInt8) {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_auth(self.uniffiClonePointer(),
        FfiConverterUInt8.lower(reasonCode),$0
    )
}
}
    
open func connect() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_connect(self.uniffiClonePointer(),$0
    )
}
}
    
open func disconnect() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func getVersion() -> UInt8 {
    return try!  FfiConverterUInt8.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_get_version(self.uniffiClonePointer(),$0
    )
})
}
    
open func handleConnectionLost() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_handle_connection_lost(self.uniffiClonePointer(),$0
    )
}
}
    
open func handleIncoming(data: Data) -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_handle_incoming(self.uniffiClonePointer(),
        FfiConverterData.lower(data),$0
    )
})
}
    
open func handleTick(nowMs: UInt64) -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_handle_tick(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func nextTickMs() -> Int64 {
    return try!  FfiConverterInt64.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_next_tick_ms(self.uniffiClonePointer(),$0
    )
})
}
    
open func publish(topic: String, payload: Data, qos: UInt8, priority: UInt8?) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_publish(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),
        FfiConverterData.lower(payload),
        FfiConverterUInt8.lower(qos),
        FfiConverterOptionUInt8.lower(priority),$0
    )
})
}
    
open func pushEventFfi(event: MqttEventFfi) {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_push_event_ffi(self.uniffiClonePointer(),
        FfiConverterTypeMqttEventFFI.lower(event),$0
    )
}
}
    
open func subscribe(topicFilter: String, qos: UInt8) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_subscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),
        FfiConverterUInt8.lower(qos),$0
    )
})
}
    
open func takeEvents() -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_take_events(self.uniffiClonePointer(),$0
    )
})
}
    
open func takeOutgoing() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_take_outgoing(self.uniffiClonePointer(),$0
    )
})
}
    
open func unsubscribe(topicFilter: String) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqttengineffi_unsubscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttEngineFFI: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MqttEngineFfi

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttEngineFfi {
        return MqttEngineFfi(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MqttEngineFfi) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttEngineFfi {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MqttEngineFfi, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEngineFFI_lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttEngineFfi {
    return try FfiConverterTypeMqttEngineFFI.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEngineFFI_lower(_ value: MqttEngineFfi) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMqttEngineFFI.lower(value)
}




public protocol MqttEventListFfiProtocol : AnyObject {
    
    func get(index: UInt32)  -> MqttEventFfi?
    
    func isEmpty()  -> Bool
    
    func len()  -> UInt32
    
}

open class MqttEventListFfi:
    MqttEventListFfiProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_flowsdk_ffi_fn_clone_mqtteventlistffi(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_flowsdk_ffi_fn_free_mqtteventlistffi(pointer, $0) }
    }

    

    
open func get(index: UInt32) -> MqttEventFfi? {
    return try!  FfiConverterOptionTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqtteventlistffi_get(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
open func isEmpty() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqtteventlistffi_is_empty(self.uniffiClonePointer(),$0
    )
})
}
    
open func len() -> UInt32 {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_mqtteventlistffi_len(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttEventListFFI: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MqttEventListFfi

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttEventListFfi {
        return MqttEventListFfi(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MqttEventListFfi) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttEventListFfi {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MqttEventListFfi, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEventListFFI_lift(_ pointer: UnsafeMutableRawPointer) throws -> MqttEventListFfi {
    return try FfiConverterTypeMqttEventListFFI.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEventListFFI_lower(_ value: MqttEventListFfi) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMqttEventListFFI.lower(value)
}




public protocol QuicMqttEngineFfiProtocol : AnyObject {
    
    func connect(serverAddr: String, serverName: String, tlsOpts: MqttTlsOptionsFfi, nowMs: UInt64) 
    
    func disconnect() 
    
    func handleDatagram(data: Data, remoteAddr: String, nowMs: UInt64) 
    
    func handleTick(nowMs: UInt64)  -> [MqttEventFfi]
    
    func isConnected()  -> Bool
    
    func publish(topic: String, payload: Data, qos: UInt8)  -> Int32
    
    func subscribe(topicFilter: String, qos: UInt8)  -> Int32
    
    func takeEvents()  -> [MqttEventFfi]
    
    func takeOutgoingDatagrams()  -> [MqttDatagramFfi]
    
    func unsubscribe(topicFilter: String)  -> Int32
    
}

open class QuicMqttEngineFfi:
    QuicMqttEngineFfiProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_flowsdk_ffi_fn_clone_quicmqttengineffi(self.pointer, $0) }
    }
public convenience init(opts: MqttOptionsFfi) {
    let pointer =
        try! rustCall() {
    uniffi_flowsdk_ffi_fn_constructor_quicmqttengineffi_new(
        FfiConverterTypeMqttOptionsFFI.lower(opts),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_flowsdk_ffi_fn_free_quicmqttengineffi(pointer, $0) }
    }

    

    
open func connect(serverAddr: String, serverName: String, tlsOpts: MqttTlsOptionsFfi, nowMs: UInt64) {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_connect(self.uniffiClonePointer(),
        FfiConverterString.lower(serverAddr),
        FfiConverterString.lower(serverName),
        FfiConverterTypeMqttTlsOptionsFFI.lower(tlsOpts),
        FfiConverterUInt64.lower(nowMs),$0
    )
}
}
    
open func disconnect() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func handleDatagram(data: Data, remoteAddr: String, nowMs: UInt64) {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_handle_datagram(self.uniffiClonePointer(),
        FfiConverterData.lower(data),
        FfiConverterString.lower(remoteAddr),
        FfiConverterUInt64.lower(nowMs),$0
    )
}
}
    
open func handleTick(nowMs: UInt64) -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_handle_tick(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func publish(topic: String, payload: Data, qos: UInt8) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_publish(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),
        FfiConverterData.lower(payload),
        FfiConverterUInt8.lower(qos),$0
    )
})
}
    
open func subscribe(topicFilter: String, qos: UInt8) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_subscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),
        FfiConverterUInt8.lower(qos),$0
    )
})
}
    
open func takeEvents() -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_take_events(self.uniffiClonePointer(),$0
    )
})
}
    
open func takeOutgoingDatagrams() -> [MqttDatagramFfi] {
    return try!  FfiConverterSequenceTypeMqttDatagramFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_take_outgoing_datagrams(self.uniffiClonePointer(),$0
    )
})
}
    
open func unsubscribe(topicFilter: String) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_quicmqttengineffi_unsubscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeQuicMqttEngineFFI: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = QuicMqttEngineFfi

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> QuicMqttEngineFfi {
        return QuicMqttEngineFfi(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: QuicMqttEngineFfi) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> QuicMqttEngineFfi {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: QuicMqttEngineFfi, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicMqttEngineFFI_lift(_ pointer: UnsafeMutableRawPointer) throws -> QuicMqttEngineFfi {
    return try FfiConverterTypeQuicMqttEngineFFI.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeQuicMqttEngineFFI_lower(_ value: QuicMqttEngineFfi) -> UnsafeMutableRawPointer {
    return FfiConverterTypeQuicMqttEngineFFI.lower(value)
}




public protocol TlsMqttEngineFfiProtocol : AnyObject {
    
    func connect() 
    
    func disconnect() 
    
    func handleSocketData(data: Data) 
    
    func handleTick(nowMs: UInt64)  -> [MqttEventFfi]
    
    func isConnected()  -> Bool
    
    func publish(topic: String, payload: Data, qos: UInt8)  -> Int32
    
    func subscribe(topicFilter: String, qos: UInt8)  -> Int32
    
    func takeEvents()  -> [MqttEventFfi]
    
    func takeSocketData()  -> Data
    
    func unsubscribe(topicFilter: String)  -> Int32
    
}

open class TlsMqttEngineFfi:
    TlsMqttEngineFfiProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_flowsdk_ffi_fn_clone_tlsmqttengineffi(self.pointer, $0) }
    }
public convenience init(opts: MqttOptionsFfi, tlsOpts: MqttTlsOptionsFfi, serverName: String) {
    let pointer =
        try! rustCall() {
    uniffi_flowsdk_ffi_fn_constructor_tlsmqttengineffi_new(
        FfiConverterTypeMqttOptionsFFI.lower(opts),
        FfiConverterTypeMqttTlsOptionsFFI.lower(tlsOpts),
        FfiConverterString.lower(serverName),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_flowsdk_ffi_fn_free_tlsmqttengineffi(pointer, $0) }
    }

    

    
open func connect() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_connect(self.uniffiClonePointer(),$0
    )
}
}
    
open func disconnect() {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_disconnect(self.uniffiClonePointer(),$0
    )
}
}
    
open func handleSocketData(data: Data) {try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_handle_socket_data(self.uniffiClonePointer(),
        FfiConverterData.lower(data),$0
    )
}
}
    
open func handleTick(nowMs: UInt64) -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_handle_tick(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
open func isConnected() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_is_connected(self.uniffiClonePointer(),$0
    )
})
}
    
open func publish(topic: String, payload: Data, qos: UInt8) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_publish(self.uniffiClonePointer(),
        FfiConverterString.lower(topic),
        FfiConverterData.lower(payload),
        FfiConverterUInt8.lower(qos),$0
    )
})
}
    
open func subscribe(topicFilter: String, qos: UInt8) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_subscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),
        FfiConverterUInt8.lower(qos),$0
    )
})
}
    
open func takeEvents() -> [MqttEventFfi] {
    return try!  FfiConverterSequenceTypeMqttEventFFI.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_take_events(self.uniffiClonePointer(),$0
    )
})
}
    
open func takeSocketData() -> Data {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_take_socket_data(self.uniffiClonePointer(),$0
    )
})
}
    
open func unsubscribe(topicFilter: String) -> Int32 {
    return try!  FfiConverterInt32.lift(try! rustCall() {
    uniffi_flowsdk_ffi_fn_method_tlsmqttengineffi_unsubscribe(self.uniffiClonePointer(),
        FfiConverterString.lower(topicFilter),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTlsMqttEngineFFI: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TlsMqttEngineFfi

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TlsMqttEngineFfi {
        return TlsMqttEngineFfi(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TlsMqttEngineFfi) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TlsMqttEngineFfi {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TlsMqttEngineFfi, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTlsMqttEngineFFI_lift(_ pointer: UnsafeMutableRawPointer) throws -> TlsMqttEngineFfi {
    return try FfiConverterTypeTlsMqttEngineFFI.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTlsMqttEngineFFI_lower(_ value: TlsMqttEngineFfi) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTlsMqttEngineFFI.lower(value)
}


public struct ConnectionResultFfi {
    public var reasonCode: UInt8
    public var sessionPresent: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(reasonCode: UInt8, sessionPresent: Bool) {
        self.reasonCode = reasonCode
        self.sessionPresent = sessionPresent
    }
}



extension ConnectionResultFfi: Equatable, Hashable {
    public static func ==(lhs: ConnectionResultFfi, rhs: ConnectionResultFfi) -> Bool {
        if lhs.reasonCode != rhs.reasonCode {
            return false
        }
        if lhs.sessionPresent != rhs.sessionPresent {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(reasonCode)
        hasher.combine(sessionPresent)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConnectionResultFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ConnectionResultFfi {
        return
            try ConnectionResultFfi(
                reasonCode: FfiConverterUInt8.read(from: &buf), 
                sessionPresent: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ConnectionResultFfi, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.reasonCode, into: &buf)
        FfiConverterBool.write(value.sessionPresent, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionResultFFI_lift(_ buf: RustBuffer) throws -> ConnectionResultFfi {
    return try FfiConverterTypeConnectionResultFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConnectionResultFFI_lower(_ value: ConnectionResultFfi) -> RustBuffer {
    return FfiConverterTypeConnectionResultFFI.lower(value)
}


public struct MqttDatagramFfi {
    public var addr: String
    public var data: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(addr: String, data: Data) {
        self.addr = addr
        self.data = data
    }
}



extension MqttDatagramFfi: Equatable, Hashable {
    public static func ==(lhs: MqttDatagramFfi, rhs: MqttDatagramFfi) -> Bool {
        if lhs.addr != rhs.addr {
            return false
        }
        if lhs.data != rhs.data {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(addr)
        hasher.combine(data)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttDatagramFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttDatagramFfi {
        return
            try MqttDatagramFfi(
                addr: FfiConverterString.read(from: &buf), 
                data: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MqttDatagramFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.addr, into: &buf)
        FfiConverterData.write(value.data, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttDatagramFFI_lift(_ buf: RustBuffer) throws -> MqttDatagramFfi {
    return try FfiConverterTypeMqttDatagramFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttDatagramFFI_lower(_ value: MqttDatagramFfi) -> RustBuffer {
    return FfiConverterTypeMqttDatagramFFI.lower(value)
}


public struct MqttMessageFfi {
    public var topic: String
    public var payload: Data
    public var qos: UInt8
    public var retain: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(topic: String, payload: Data, qos: UInt8, retain: Bool) {
        self.topic = topic
        self.payload = payload
        self.qos = qos
        self.retain = retain
    }
}



extension MqttMessageFfi: Equatable, Hashable {
    public static func ==(lhs: MqttMessageFfi, rhs: MqttMessageFfi) -> Bool {
        if lhs.topic != rhs.topic {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        if lhs.qos != rhs.qos {
            return false
        }
        if lhs.retain != rhs.retain {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(topic)
        hasher.combine(payload)
        hasher.combine(qos)
        hasher.combine(retain)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttMessageFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttMessageFfi {
        return
            try MqttMessageFfi(
                topic: FfiConverterString.read(from: &buf), 
                payload: FfiConverterData.read(from: &buf), 
                qos: FfiConverterUInt8.read(from: &buf), 
                retain: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MqttMessageFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.topic, into: &buf)
        FfiConverterData.write(value.payload, into: &buf)
        FfiConverterUInt8.write(value.qos, into: &buf)
        FfiConverterBool.write(value.retain, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttMessageFFI_lift(_ buf: RustBuffer) throws -> MqttMessageFfi {
    return try FfiConverterTypeMqttMessageFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttMessageFFI_lower(_ value: MqttMessageFfi) -> RustBuffer {
    return FfiConverterTypeMqttMessageFFI.lower(value)
}


public struct MqttOptionsFfi {
    public var clientId: String
    public var mqttVersion: UInt8
    public var cleanStart: Bool
    public var keepAlive: UInt16
    public var username: String?
    public var password: String?
    public var reconnectBaseDelayMs: UInt64
    public var reconnectMaxDelayMs: UInt64
    public var maxReconnectAttempts: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(clientId: String, mqttVersion: UInt8, cleanStart: Bool, keepAlive: UInt16, username: String?, password: String?, reconnectBaseDelayMs: UInt64, reconnectMaxDelayMs: UInt64, maxReconnectAttempts: UInt32) {
        self.clientId = clientId
        self.mqttVersion = mqttVersion
        self.cleanStart = cleanStart
        self.keepAlive = keepAlive
        self.username = username
        self.password = password
        self.reconnectBaseDelayMs = reconnectBaseDelayMs
        self.reconnectMaxDelayMs = reconnectMaxDelayMs
        self.maxReconnectAttempts = maxReconnectAttempts
    }
}



extension MqttOptionsFfi: Equatable, Hashable {
    public static func ==(lhs: MqttOptionsFfi, rhs: MqttOptionsFfi) -> Bool {
        if lhs.clientId != rhs.clientId {
            return false
        }
        if lhs.mqttVersion != rhs.mqttVersion {
            return false
        }
        if lhs.cleanStart != rhs.cleanStart {
            return false
        }
        if lhs.keepAlive != rhs.keepAlive {
            return false
        }
        if lhs.username != rhs.username {
            return false
        }
        if lhs.password != rhs.password {
            return false
        }
        if lhs.reconnectBaseDelayMs != rhs.reconnectBaseDelayMs {
            return false
        }
        if lhs.reconnectMaxDelayMs != rhs.reconnectMaxDelayMs {
            return false
        }
        if lhs.maxReconnectAttempts != rhs.maxReconnectAttempts {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(clientId)
        hasher.combine(mqttVersion)
        hasher.combine(cleanStart)
        hasher.combine(keepAlive)
        hasher.combine(username)
        hasher.combine(password)
        hasher.combine(reconnectBaseDelayMs)
        hasher.combine(reconnectMaxDelayMs)
        hasher.combine(maxReconnectAttempts)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttOptionsFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttOptionsFfi {
        return
            try MqttOptionsFfi(
                clientId: FfiConverterString.read(from: &buf), 
                mqttVersion: FfiConverterUInt8.read(from: &buf), 
                cleanStart: FfiConverterBool.read(from: &buf), 
                keepAlive: FfiConverterUInt16.read(from: &buf), 
                username: FfiConverterOptionString.read(from: &buf), 
                password: FfiConverterOptionString.read(from: &buf), 
                reconnectBaseDelayMs: FfiConverterUInt64.read(from: &buf), 
                reconnectMaxDelayMs: FfiConverterUInt64.read(from: &buf), 
                maxReconnectAttempts: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: MqttOptionsFfi, into buf: inout [UInt8]) {
        FfiConverterString.write(value.clientId, into: &buf)
        FfiConverterUInt8.write(value.mqttVersion, into: &buf)
        FfiConverterBool.write(value.cleanStart, into: &buf)
        FfiConverterUInt16.write(value.keepAlive, into: &buf)
        FfiConverterOptionString.write(value.username, into: &buf)
        FfiConverterOptionString.write(value.password, into: &buf)
        FfiConverterUInt64.write(value.reconnectBaseDelayMs, into: &buf)
        FfiConverterUInt64.write(value.reconnectMaxDelayMs, into: &buf)
        FfiConverterUInt32.write(value.maxReconnectAttempts, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttOptionsFFI_lift(_ buf: RustBuffer) throws -> MqttOptionsFfi {
    return try FfiConverterTypeMqttOptionsFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttOptionsFFI_lower(_ value: MqttOptionsFfi) -> RustBuffer {
    return FfiConverterTypeMqttOptionsFFI.lower(value)
}


public struct MqttTlsOptionsFfi {
    public var caCertFile: String?
    public var clientCertFile: String?
    public var clientKeyFile: String?
    public var insecureSkipVerify: Bool
    public var alpnProtocols: [String]
    public var enableKeyLog: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(caCertFile: String?, clientCertFile: String?, clientKeyFile: String?, insecureSkipVerify: Bool, alpnProtocols: [String], enableKeyLog: Bool) {
        self.caCertFile = caCertFile
        self.clientCertFile = clientCertFile
        self.clientKeyFile = clientKeyFile
        self.insecureSkipVerify = insecureSkipVerify
        self.alpnProtocols = alpnProtocols
        self.enableKeyLog = enableKeyLog
    }
}



extension MqttTlsOptionsFfi: Equatable, Hashable {
    public static func ==(lhs: MqttTlsOptionsFfi, rhs: MqttTlsOptionsFfi) -> Bool {
        if lhs.caCertFile != rhs.caCertFile {
            return false
        }
        if lhs.clientCertFile != rhs.clientCertFile {
            return false
        }
        if lhs.clientKeyFile != rhs.clientKeyFile {
            return false
        }
        if lhs.insecureSkipVerify != rhs.insecureSkipVerify {
            return false
        }
        if lhs.alpnProtocols != rhs.alpnProtocols {
            return false
        }
        if lhs.enableKeyLog != rhs.enableKeyLog {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(caCertFile)
        hasher.combine(clientCertFile)
        hasher.combine(clientKeyFile)
        hasher.combine(insecureSkipVerify)
        hasher.combine(alpnProtocols)
        hasher.combine(enableKeyLog)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttTlsOptionsFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttTlsOptionsFfi {
        return
            try MqttTlsOptionsFfi(
                caCertFile: FfiConverterOptionString.read(from: &buf), 
                clientCertFile: FfiConverterOptionString.read(from: &buf), 
                clientKeyFile: FfiConverterOptionString.read(from: &buf), 
                insecureSkipVerify: FfiConverterBool.read(from: &buf), 
                alpnProtocols: FfiConverterSequenceString.read(from: &buf), 
                enableKeyLog: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MqttTlsOptionsFfi, into buf: inout [UInt8]) {
        FfiConverterOptionString.write(value.caCertFile, into: &buf)
        FfiConverterOptionString.write(value.clientCertFile, into: &buf)
        FfiConverterOptionString.write(value.clientKeyFile, into: &buf)
        FfiConverterBool.write(value.insecureSkipVerify, into: &buf)
        FfiConverterSequenceString.write(value.alpnProtocols, into: &buf)
        FfiConverterBool.write(value.enableKeyLog, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttTlsOptionsFFI_lift(_ buf: RustBuffer) throws -> MqttTlsOptionsFfi {
    return try FfiConverterTypeMqttTlsOptionsFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttTlsOptionsFFI_lower(_ value: MqttTlsOptionsFfi) -> RustBuffer {
    return FfiConverterTypeMqttTlsOptionsFFI.lower(value)
}


public struct PublishResultFfi {
    public var packetId: UInt16?
    public var reasonCode: UInt8?
    public var qos: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(packetId: UInt16?, reasonCode: UInt8?, qos: UInt8) {
        self.packetId = packetId
        self.reasonCode = reasonCode
        self.qos = qos
    }
}



extension PublishResultFfi: Equatable, Hashable {
    public static func ==(lhs: PublishResultFfi, rhs: PublishResultFfi) -> Bool {
        if lhs.packetId != rhs.packetId {
            return false
        }
        if lhs.reasonCode != rhs.reasonCode {
            return false
        }
        if lhs.qos != rhs.qos {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(packetId)
        hasher.combine(reasonCode)
        hasher.combine(qos)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePublishResultFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublishResultFfi {
        return
            try PublishResultFfi(
                packetId: FfiConverterOptionUInt16.read(from: &buf), 
                reasonCode: FfiConverterOptionUInt8.read(from: &buf), 
                qos: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: PublishResultFfi, into buf: inout [UInt8]) {
        FfiConverterOptionUInt16.write(value.packetId, into: &buf)
        FfiConverterOptionUInt8.write(value.reasonCode, into: &buf)
        FfiConverterUInt8.write(value.qos, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublishResultFFI_lift(_ buf: RustBuffer) throws -> PublishResultFfi {
    return try FfiConverterTypePublishResultFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublishResultFFI_lower(_ value: PublishResultFfi) -> RustBuffer {
    return FfiConverterTypePublishResultFFI.lower(value)
}


public struct SubscribeResultFfi {
    public var packetId: UInt16
    public var reasonCodes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(packetId: UInt16, reasonCodes: Data) {
        self.packetId = packetId
        self.reasonCodes = reasonCodes
    }
}



extension SubscribeResultFfi: Equatable, Hashable {
    public static func ==(lhs: SubscribeResultFfi, rhs: SubscribeResultFfi) -> Bool {
        if lhs.packetId != rhs.packetId {
            return false
        }
        if lhs.reasonCodes != rhs.reasonCodes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(packetId)
        hasher.combine(reasonCodes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSubscribeResultFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SubscribeResultFfi {
        return
            try SubscribeResultFfi(
                packetId: FfiConverterUInt16.read(from: &buf), 
                reasonCodes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SubscribeResultFfi, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.packetId, into: &buf)
        FfiConverterData.write(value.reasonCodes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubscribeResultFFI_lift(_ buf: RustBuffer) throws -> SubscribeResultFfi {
    return try FfiConverterTypeSubscribeResultFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSubscribeResultFFI_lower(_ value: SubscribeResultFfi) -> RustBuffer {
    return FfiConverterTypeSubscribeResultFFI.lower(value)
}


public struct UnsubscribeResultFfi {
    public var packetId: UInt16
    public var reasonCodes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(packetId: UInt16, reasonCodes: Data) {
        self.packetId = packetId
        self.reasonCodes = reasonCodes
    }
}



extension UnsubscribeResultFfi: Equatable, Hashable {
    public static func ==(lhs: UnsubscribeResultFfi, rhs: UnsubscribeResultFfi) -> Bool {
        if lhs.packetId != rhs.packetId {
            return false
        }
        if lhs.reasonCodes != rhs.reasonCodes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(packetId)
        hasher.combine(reasonCodes)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUnsubscribeResultFFI: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UnsubscribeResultFfi {
        return
            try UnsubscribeResultFfi(
                packetId: FfiConverterUInt16.read(from: &buf), 
                reasonCodes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: UnsubscribeResultFfi, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.packetId, into: &buf)
        FfiConverterData.write(value.reasonCodes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUnsubscribeResultFFI_lift(_ buf: RustBuffer) throws -> UnsubscribeResultFfi {
    return try FfiConverterTypeUnsubscribeResultFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUnsubscribeResultFFI_lower(_ value: UnsubscribeResultFfi) -> RustBuffer {
    return FfiConverterTypeUnsubscribeResultFFI.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum MqttEventFfi {
    
    case connected(ConnectionResultFfi
    )
    case disconnected(reasonCode: UInt8?
    )
    case messageReceived(MqttMessageFfi
    )
    case published(PublishResultFfi
    )
    case subscribed(SubscribeResultFfi
    )
    case unsubscribed(UnsubscribeResultFfi
    )
    case pingResponse(success: Bool
    )
    case error(message: String
    )
    case reconnectNeeded
    case reconnectScheduled(attempt: UInt32, delayMs: UInt64
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMqttEventFFI: FfiConverterRustBuffer {
    typealias SwiftType = MqttEventFfi

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MqttEventFfi {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .connected(try FfiConverterTypeConnectionResultFFI.read(from: &buf)
        )
        
        case 2: return .disconnected(reasonCode: try FfiConverterOptionUInt8.read(from: &buf)
        )
        
        case 3: return .messageReceived(try FfiConverterTypeMqttMessageFFI.read(from: &buf)
        )
        
        case 4: return .published(try FfiConverterTypePublishResultFFI.read(from: &buf)
        )
        
        case 5: return .subscribed(try FfiConverterTypeSubscribeResultFFI.read(from: &buf)
        )
        
        case 6: return .unsubscribed(try FfiConverterTypeUnsubscribeResultFFI.read(from: &buf)
        )
        
        case 7: return .pingResponse(success: try FfiConverterBool.read(from: &buf)
        )
        
        case 8: return .error(message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .reconnectNeeded
        
        case 10: return .reconnectScheduled(attempt: try FfiConverterUInt32.read(from: &buf), delayMs: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MqttEventFfi, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .connected(v1):
            writeInt(&buf, Int32(1))
            FfiConverterTypeConnectionResultFFI.write(v1, into: &buf)
            
        
        case let .disconnected(reasonCode):
            writeInt(&buf, Int32(2))
            FfiConverterOptionUInt8.write(reasonCode, into: &buf)
            
        
        case let .messageReceived(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypeMqttMessageFFI.write(v1, into: &buf)
            
        
        case let .published(v1):
            writeInt(&buf, Int32(4))
            FfiConverterTypePublishResultFFI.write(v1, into: &buf)
            
        
        case let .subscribed(v1):
            writeInt(&buf, Int32(5))
            FfiConverterTypeSubscribeResultFFI.write(v1, into: &buf)
            
        
        case let .unsubscribed(v1):
            writeInt(&buf, Int32(6))
            FfiConverterTypeUnsubscribeResultFFI.write(v1, into: &buf)
            
        
        case let .pingResponse(success):
            writeInt(&buf, Int32(7))
            FfiConverterBool.write(success, into: &buf)
            
        
        case let .error(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        
        case .reconnectNeeded:
            writeInt(&buf, Int32(9))
        
        
        case let .reconnectScheduled(attempt,delayMs):
            writeInt(&buf, Int32(10))
            FfiConverterUInt32.write(attempt, into: &buf)
            FfiConverterUInt64.write(delayMs, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEventFFI_lift(_ buf: RustBuffer) throws -> MqttEventFfi {
    return try FfiConverterTypeMqttEventFFI.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMqttEventFFI_lower(_ value: MqttEventFfi) -> RustBuffer {
    return FfiConverterTypeMqttEventFFI.lower(value)
}



extension MqttEventFfi: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeMqttEventFFI: FfiConverterRustBuffer {
    typealias SwiftType = MqttEventFfi?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeMqttEventFFI.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeMqttEventFFI.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMqttDatagramFFI: FfiConverterRustBuffer {
    typealias SwiftType = [MqttDatagramFfi]

    public static func write(_ value: [MqttDatagramFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMqttDatagramFFI.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MqttDatagramFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [MqttDatagramFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMqttDatagramFFI.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMqttEventFFI: FfiConverterRustBuffer {
    typealias SwiftType = [MqttEventFfi]

    public static func write(_ value: [MqttEventFfi], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMqttEventFFI.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [MqttEventFfi] {
        let len: Int32 = try readInt(&buf)
        var seq = [MqttEventFfi]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMqttEventFFI.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_flowsdk_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_auth() != 13274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_connect() != 11843) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_disconnect() != 35275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_get_version() != 19826) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_handle_connection_lost() != 12358) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_handle_incoming() != 55488) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_handle_tick() != 40864) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_is_connected() != 33756) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_next_tick_ms() != 63992) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_publish() != 44572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_push_event_ffi() != 16806) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_subscribe() != 31682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_take_events() != 17921) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_take_outgoing() != 12337) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqttengineffi_unsubscribe() != 51097) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqtteventlistffi_get() != 5088) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqtteventlistffi_is_empty() != 43194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_mqtteventlistffi_len() != 36035) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_connect() != 39570) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_disconnect() != 54076) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_handle_datagram() != 34322) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_handle_tick() != 39076) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_is_connected() != 53863) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_publish() != 17969) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_subscribe() != 16787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_take_events() != 34914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_take_outgoing_datagrams() != 32224) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_quicmqttengineffi_unsubscribe() != 48) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_connect() != 53946) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_disconnect() != 58642) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_handle_socket_data() != 27993) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_handle_tick() != 57570) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_is_connected() != 11670) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_publish() != 29858) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_subscribe() != 35959) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_take_events() != 41728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_take_socket_data() != 6663) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_method_tlsmqttengineffi_unsubscribe() != 21790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_constructor_mqttengineffi_new() != 63280) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_constructor_mqttengineffi_new_with_opts() != 49926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_constructor_quicmqttengineffi_new() != 4296) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_flowsdk_ffi_checksum_constructor_tlsmqttengineffi_new() != 55234) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all