name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      run: |
        rustup toolchain install stable
        rustup default stable

    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: '25.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install mosquitto
      run: |
        sudo apt-get update
        sudo apt-get install -y mosquitto mosquitto-clients

    - name: Make test script executable
      run: chmod +x mqtt_grpc_duality/run_integration_tests.sh

    - name: Run integration 
      timeout-minutes: 20
      working-directory: mqtt_grpc_duality
      run: RUST_BACKTRACE=full ./run_integration_tests.sh
